version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
  
  pre_build:
    commands:
      - echo Installing Frontend dependencies...
      - cd Frontend && npm ci
      - echo Installing Backend dependencies...
      - cd ../Backend && npm ci
  
  build:
    commands:
      - echo Building Frontend...
      - cd Frontend && npm run build
      - echo Generating Prisma client...
      - cd ../Backend && npm run db:generate
  
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  discard-paths: no
